version: '3.8'

services:
  web:
    depends_on:
      - api
    build:
      context: ./frontend
    ports:
      - 5173:5173
    stdin_open: true
    environment:
      VITE_API_URL: http://localhost:8000
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /usr/src/app
          action: sync
          ignore:
            - ./frontend/node_modules/

  api:
    depends_on:
      - db
    build:
      context: ./backend
    ports:
      - 8000:8000
    environment:
      DB_URL: mongodb://db/anime
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /usr/src/app
          action: sync
          ignore:
            - ./backend/node_modules/

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - anime:/data/db

volumes:
  anime:
